### ISSUE TITLE
Feature Request : Extra Samba Option

### ISSUE THREAD

**Issue by adenau** [rehanone/puppet-samba#31]
I would like to add additional options to my samba configuration, either at the global level or at the share level. For example, I would like to allow my users to have a recycling bin (https://lonewolfonline.net/enabling-recycle-bin-functionality-samba/).  I don't expect that this puppet module would do everything, but Is there already a way to specify additional arbitrary options?

Thank you for the great work, this module is very useful.

**Comment by bschonec** [comment]
Printer/CUPS functionality would be welcome, too.  Is this project still alive?

**Comment by bschonec** [comment]
@adenau , are you still in need of this feature?  I think I can add this without too much trouble.

**Comment by adenau** [comment]
I'll be honest, I moved on to Ansible about a year ago. I still think that Puppet is a better product, and I miss it a lot, but the module development has slowed down to much in the last few years. Apologies for forgetting to close this request.

**Comment by arusso** [comment]
I'm still using the module and would like to see this.

**Comment by parkr** [comment]
I'd like to see support for the following options:

```
server multi channel support = yes
aio read size = 1
aio write size = 1
min receivefile size = 16384
```

Multi-channel support is a big boon for speed these days.

I don't see them supported here: https://github.com/rehanone/puppet-samba/blob/5abd50865a3377b60a9cc76ed8f718c50f7bddab/manifests/config.pp

I'll send a pull request.

**Comment by parkr** [comment]
PR sent (#52). To test this, add hiera like:

```yaml
samba::additional_config:
  your_config: its_new_value
```

I'm using this in my `Puppetfile`:

```ruby
mod "rehanone-samba",
  :git => "https://github.com/parkr/puppet-samba",
  :branch =>  "arbitrary-config"
```

This produces the following in your `/etc/samba/smb.conf`:

```conf
[global]
  your config = its_new_value
```
