### ISSUE TITLE
'ntlm auth' is not a boolean

### ISSUE THREAD

**Issue by bschonec** [rehanone/puppet-samba#39]
From the [Samba Docs](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#CLIENTIPCSIGNING), ntlm auth configuration CAN be yes/no but also can be one of the following values:

- ntlmv1-permitted (alias yes) 
- ntlmv2-only (alias no)
- mschapv2-and-ntlmv2-only
- disabled

The [source code](https://github.com/rehanone/puppet-samba/blob/2d8f222fbf74ebebf9233341987c93eac7da746a/manifests/init.pp#L61) shows that the config is a boolean and it should be changed to either a string, or (preferable) a

Variant[Enum['ntlmv1-permitted', 'ntlmv2-only', 'mschapv2-and-ntlmv2-only', 'disabled'], Boolean] 

#40

**Comment by rehanone** [comment]
Thanks for providing the information about this. I unfortunately don't find much time working on this module so it may be long time before I get a chance to update it. A PR for this change would be more than welcome.

**Comment by bschonec** [comment]
Any chance you'd be willing to transfer ownership of the project?  Your module is used by a lot of VoxPupuli users.  I'd be willing to take over the project if you're willing; I've already made a lot of changes that I intend to submit.

**Comment by rehanone** [comment]
@bschonec , thanks for offering to take care of this module. Perhaps, I would consider that in the future. At this point however, I am happy to give you the commit access. However, there needs to be a plan for these 2 issues first:

- A way to update module to use current PDK version.
- Fix the TavisCI tests and a way for migrating this from TravisCI to possibly Github Actions.

I would add these two as issues for this modules. I feel a bit reluctant to merge PRs without a successful test harness and I struggle to update PDK templates to later versions So any help in this regard would a great help.

**Comment by bschonec** [comment]
I don't think the Voxpupuli team cares about the Puppet PDK.  In fact, I think they avoid it and develop tests only with Github actions now.  I know next to nothing about writing tests but I am pretty sure that they stay away from the PDK.

**Comment by rehanone** [comment]
Yes I guess that makes sense because I do remember reading somewhere that PDK has been deprecated. I guess in that case the test just needs to be migrated to some framework that allows some sort of testing for this module

**Comment by bschonec** [comment]
Resolved by #40
