### ISSUE TITLE
Update parameter defaults to match smb.conf man page?

### ISSUE THREAD

**Issue by bschonec** [rehanone/puppet-samba#47]
Since I'm doing a bunch of work on the module anyway, should I update the parameters in the class modules to match the [Samba defaults](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html)?

I've consulted with the Voxpupuli crowd and they recommended that the default values be removed from the ./data/common.yml file and placed into the individual class module files (init.pp, option.pp, etc).  Doing this also helps with [documentation](https://www.puppet.com/docs/puppet/8/puppet_strings.html).

**Comment by rehanone** [comment]
> Since I'm doing a bunch of work on the module anyway, should I update the parameters in the class modules to match the [Samba defaults](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html)?
> 

I think this is a good thing for sure so absolutely yes!

> I've consulted with the Voxpupuli crowd and they recommended that the default values be removed from the ./data/common.yml file and placed into the individual class module files (init.pp, option.pp, etc). Doing this also helps with [documentation](https://www.puppet.com/docs/puppet/8/puppet_strings.html).

Well they reason I converted it to use yml files for default values was I think it is the recommend way from puppet labs. Even though I personally prefer yml files, I guess I am not opposes to the idea of following the Voxpupuli recommendation as this module is already using that for testing.

I would suggest make these changes as separately PRs so they can be merged independently.

**Comment by bschonec** [comment]
Resolved by #49 and #50
